name: austin # you probably want to 'snapcraft register <name>'
version: '0.7.0+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Python frame stack sampler for CPython # 79 char long summary
description: |
  Austin is a Python frame stack sampler for CPython written in pure C. It
  samples the stack traces of a Python application so that they can be
  visualised and analysed. As such, it serves the basis for building powerful
  profilers for Python.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

parts:
  austin:
    plugin: autotools
    source: git://github.com/P403n1x87/austin
    source-depth: 1

apps:
  austin:
    command: bin/austin
