name: austin
base: core20
# [[[cog
# from scripts.utils import get_current_version_from_changelog as version
# print(f"version: '{version()}+git'")
# ]]]
version: '3.7.0+git'
# [[[end]]]
summary: A Python frame stack sampler for CPython
description: |
  Austin is a Python frame stack sampler for CPython written in pure C. It
  samples the stack traces of a Python application so that they can be
  visualised and analysed. As such, it serves the basis for building powerful
  profilers for Python.

grade: stable
confinement: classic

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

parts:
  austin:
    plugin: autotools
    source: https://github.com/P403n1x87/austin
    source-type: git
    source-depth: 1
    build-packages: [libunwind-dev, binutils-dev, libiberty-dev, zlib1g-dev]
    stage-packages: [libbinutils]

apps:
  austin:
    command: usr/local/bin/austin
  p:
    command: usr/local/bin/austinp
