name: Benchmarks

on:
  pull_request:
    paths:
      - .github/workflows/benchmarks.yml
      - scripts/benchmark.py
      - scripts/requirements-bm.txt
      - src/**

jobs:
  benchmarks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libunwind-dev binutils-dev libiberty-dev

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Compile Austin
        run: |
          autoreconf --install
          ./configure --enable-debug-symbols true
          make

      - name: Install runtime dependencies
        run: |
          python3.10 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r scripts/requirements-bm.txt

      - name: Run benchmarks
        env:
          PYTHONPATH: "."
        run: |
          ulimit -c unlimited
          echo "core.%p" | sudo tee /proc/sys/kernel/core_pattern
          source .venv/bin/activate
          python scripts/benchmark.py --format markdown --last | tee comment.txt

      - name: Post results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: comment.txt
