name: Build (Linux archs)

on:
  push:
    branches:
      - master
      - devel
  pull_request:

jobs:
  build-linux-archs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: ["armv7", "aarch64", "ppc64le"]
      fail-fast: false
    name: Build on ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout sources
        
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build on ${{ matrix.arch }}
        id: build-on-arch
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs:  --volume "${GITHUB_WORKSPACE}/artifacts:/artifacts"
          setup: |
            mkdir -p ./artifacts
          run: ARCH=${{ matrix.arch }} bash scripts/build_arch.sh

      - name: Show artifacts
        run: |
          ls -al ./artifacts
