name: Build/Release (Linux archs)

on:
  workflow_dispatch:
    inputs:
      libunwind-version:
        description: 'libunwind git tag to build'
        default: 'v1.8.3'
  push:
    branches:
      - master
      - devel
  pull_request:
    paths:
      - .github/workflows/build_release_arch.yml
      - scripts/build_arch.sh
      - scripts/build-wheel.py
      - scripts/requirements-bw.txt
      - src/**
      - configure.ac
      - Makefile.am
  release:
    types: [published]

env:
  LIBUNWIND_VERSION: ${{ inputs.libunwind-version || 'v1.8.3' }}

permissions:
  contents: write

jobs:
  release-linux-archs:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: ["armv7", "ppc64le"]
      fail-fast: false
    name: Build on ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout sources

      - name: Cache libunwind for ${{ matrix.arch }}
        uses: actions/cache@v4
        with:
          path: .libunwind-cache
          key: libunwind-${{ matrix.arch }}-${{ env.LIBUNWIND_VERSION }}

      - uses: uraimo/run-on-arch-action@v3
        name: Build Austin on ${{ matrix.arch }}
        id: build-on-arch
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          dockerRunArgs: --volume "${GITHUB_WORKSPACE}/artifacts:/artifacts" --volume "${GITHUB_WORKSPACE}/.libunwind-cache:/libunwind-cache"
          setup: |
            mkdir -p ./artifacts .libunwind-cache
          install: |
            apt-get update
            apt-get -y install --no-install-recommends \
                autoconf \
                automake \
                build-essential \
                ca-certificates \
                libtool \
                binutils-dev \
                libiberty-dev \
                liblzma-dev \
                musl-tools \
                zlib1g-dev \
                libzstd-dev \
                git
          run: ARCH=${{ matrix.arch }} LIBUNWIND_VERSION=${{ env.LIBUNWIND_VERSION }} bash scripts/build_arch.sh

      - name: Show artifacts
        run: |
          ls -al ./artifacts

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/austin*.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build wheels on ${{ matrix.arch }}
        run: |
          python3.10 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r scripts/requirements-bw.txt
          
          export VERSION=$(cat src/austin.h | sed -r -n "s/^#define VERSION[ ]+\"(.+)\"/\1/p");

          case ${{ matrix.arch }} in
            armv7)
              PLATFORM=manylinux_2_17_armv7l.manylinux2014_armv7l
              MUSL_PLATFORM=musllinux_1_1_armv7l
              ;;
            ppc64le)
              PLATFORM=manylinux_2_17_ppc64le.manylinux2014_ppc64le
              MUSL_PLATFORM=musllinux_1_1_ppc64le
              ;;
          esac

          # FT Python has no official builds for armv7/ppc64le.
          python scripts/build-wheel.py \
            --version=$VERSION \
            --platform=$PLATFORM \
            --no-free-threaded \
            --files austin:./artifacts/austin austinp:./artifacts/austinp

          python scripts/build-wheel.py \
            --version=$VERSION \
            --platform=$MUSL_PLATFORM \
            --no-free-threaded \
            --files austin:./artifacts/austin.musl

          deactivate

      - name: Upload wheels
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          source .venv/bin/activate
          twine upload dist/*.whl --username __token__ --password ${{ secrets.PYPI_TOKEN }}s
          deactivate
