name: Build (Linux archs)

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    paths:
      - .github/workflows/build_arch.yml
      - scripts/build_arch.sh
      - scripts/build-wheel.py
      - scripts/requirements-bw.txt
      - src/**
      - configure.ac
      - Makefile.am

jobs:
  build-linux-archs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: ["armv7", "aarch64", "ppc64le"]
      fail-fast: false
    name: Build on ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout sources

      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build Austin on ${{ matrix.arch }}
        id: build-on-arch
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs:  --volume "${GITHUB_WORKSPACE}/artifacts:/artifacts"
          setup: |
            mkdir -p ./artifacts
          run: ARCH=${{ matrix.arch }} bash scripts/build_arch.sh

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build wheels on ${{ matrix.arch }}
        run: |
          python3.10 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r scripts/requirements-bw.txt
          
          export VERSION=$(cat src/austin.h | sed -r -n "s/^#define VERSION[ ]+\"(.+)\"/\1/p");

          case ${{ matrix.arch }} in
            armv7)
              PLATFORM=manylinux_2_17_armv7l.manylinux2014_armv7l
              MUSL_PLATFORM=musllinux_1_1_armv7l
              ;;
            aarch64)
              PLATFORM=manylinux_2_17_aarch64.manylinux2014_aarch64
              MUSL_PLATFORM=musllinux_1_1_aarch64
              ;;
            ppc64le)
              PLATFORM=manylinux_2_17_ppc64le.manylinux2014_ppc64le
              MUSL_PLATFORM=musllinux_1_1_ppc64le
              ;;
          esac

          python scripts/build-wheel.py \
            --version=$VERSION \
            --platform=$PLATFORM \
            --files austin:./artifacts/austin austinp:./artifacts/austinp

          python scripts/build-wheel.py \
            --version=$VERSION \
            --platform=$MUSL_PLATFORM \
            --files austin:./artifacts/austin.musl

          deactivate

      - name: Show artifacts
        run: |
          ls -al ./artifacts
